### ISSUE TITLE
Electrum-2.9.3 version

### ISSUE THREAD

**Issue by pekhota** [osminogin/docker-electrum-daemon#1]
Hi, I would like to see option for new version or some kind of tag

**Comment by ramontayag** [comment]
Here's a pull request for 3.0.5: https://github.com/osminogin/docker-electrum-daemon/pull/2

**Comment by ramontayag** [comment]
@osminogin what do you think about https://github.com/osminogin/docker-electrum-daemon/pull/3?

**Comment by osminogin** [comment]
@pekhota Container updated to latest Electrum 3.0.5 version
@ramontayag I think `LABEL version=...` is more docker way solution. So far, I don't see now the need for additional versioning or add some additional tags. The latest Electrum version is always current, so we will try to deliver it in this container.

**Comment by ramontayag** [comment]
I find tags useful when I want to install a specific version of the application/image. Is this possible with `LABEL version`? I'm not familiar with that.
