### ISSUE TITLE
(make build) ==> chown: unknown user

### ISSUE THREAD

**Issue by n0m4de** [osminogin/docker-electrum-daemon#19]
Hi,

I have this error  when i run 'make build':
`
chown: unknown user electrum
The command '/bin/sh -c mkdir -p /data ${ELECTRUM_HOME} && 	ln -sf /data ${ELECTRUM_HOME}/.electrum && 	chown ${ELECTRUM_USER} ${ELECTRUM_HOME}/.electrum /data' returned a non-zero code: 1
make: *** [Makefile:20 : docker_build] Erreur 1

If you have an idea !? :)
`

**Comment by n0m4de** [comment]
I find a solution for now, update the Dockerfile (move up add user) :

`RUN adduser -D $ELECTRUM_USER && \
	mkdir -p /data ${ELECTRUM_HOME} && \
	ln -sf /data ${ELECTRUM_HOME}/.electrum && \
	chown ${ELECTRUM_USER} ${ELECTRUM_HOME}/.electrum /data`


But now i have a new bug lol :d

Running setup.py install for cffi: started
Running setup.py install for cffi: finished with status 'error'
error: subprocess-exited-with-error

**Comment by osminogin** [comment]
I commit some changes, so check it. 

But for me is helped to set "dns": ["8.8.8.8"] in docker config and restart docker like this https://stackoverflow.com/a/71505749/1068313

Build and starts fine.

**Comment by n0m4de** [comment]
Okey i go to check it ! Thank's:)

**Comment by n0m4de** [comment]
the container is created !my solution, add alpine-sdk & libffi-dev

`RUN apk --no-cache add --virtual build-dependencies alpine-sdk libffi-dev gcc musl-dev libsecp256k1 libsecp256k1-dev libressl-dev`

**Comment by osminogin** [comment]
Thanks. There will be problems I will try this solution.
