### ISSUE TITLE
No longer able to connect to the RPC

### ISSUE THREAD

**Issue by ramontayag** [osminogin/docker-electrum-daemon#5]
On commit https://github.com/osminogin/docker-electrum-daemon/pull/2, I was able to query electrum via RPC. Now, I can't. I'm not sure why and I'll give it a shot tomorrow. Might have something to do with the removal of `socat` (whose usage I'm not familiar with).

**Comment by osminogin** [comment]
Please check your setup with `docker ps -a` and `netstat -tlpn`
I make some additional changes to your docker-compose.yml - JSONRPC port binded by default to localhost:7000
I successfully checked the current configuration. If you notice that what is really broken - please report.

**Comment by ramontayag** [comment]
I did this:

```
docker run --rm --name electrum-daemon --publish 127.0.0.1:7000:7000 osminogin/electrum-daemon
```

I also tried removing `127.0.0.1` so it binds to `0.0.0.0` but no dice.

Here's how it looks:

```
curl --data-binary '{"id":"1","method":"listaddresses"}' http://electrum:electrumz@localhost:7000                                                                                                              
curl: (52) Empty reply from server
```

**Comment by ramontayag** [comment]
Ok it lacks `electrum setconfig rpchost 0.0.0.0`, so that the daemon listens to all IPs passed through. I guess `socat` made it look like the request was coming from the same IP.

What are the security implications of setting the rpchost to `0.0.0.0`? Or do we just assume that this is taken care of by the Docker setup?

**Comment by osminogin** [comment]
This fine inside container.


2018-01-21 5:55 GMT+03:00 Ramon Tayag <notifications@github.com>:
